openapi: 3.0.0
info:
  title: Task CRUD API
  description: RESTful API for managing user tasks with JWT authentication
  version: 1.0.0
  contact:
    name: Todo App Team
  license:
    name: MIT

servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.todo-app.com/api
    description: Production server

tags:
  - name: Tasks
    description: Task management operations

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - is_complete
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 1
        user_id:
          type: string
          description: ID of user who owns this task
          example: "user-123"
        title:
          type: string
          description: Task title
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Task description (optional)
          example: "Milk, eggs, bread"
        is_complete:
          type: boolean
          description: Task completion status
          default: false
          example: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
          example: "2025-12-31T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
          example: "2025-12-31T10:00:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Task description (optional)
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Task title
          maxLength: 200
          example: "Buy groceries (updated)"
        description:
          type: string
          nullable: true
          description: Task description (optional)
          example: "Milk, eggs, bread, butter"

    TaskList:
      type: object
      required:
        - tasks
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
          description: List of tasks belonging to authenticated user

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task title is required"

paths:
  /tasks:
    get:
      summary: Get user's tasks
      description: Retrieve all tasks belonging to authenticated user
      operationId: getTasks
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskList'
        '401':
          description: Unauthorized - missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Something went wrong. Please try again."

    post:
      summary: Create new task
      description: Create a new task for authenticated user
      operationId: createTask
      tags:
        - Tasks
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                missingTitle:
                  summary: Missing title
                  value:
                    detail: "Task title is required"
                titleTooLong:
                  summary: Title exceeds 200 characters
                  value:
                    detail: "Task title cannot exceed 200 characters"
        '401':
          description: Unauthorized - missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Something went wrong. Please try again."

  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Task ID
        example: 1

    get:
      summary: Get specific task
      description: Retrieve a specific task by ID (must belong to authenticated user)
      operationId: getTask
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication required"
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "You don't have permission to access this task"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Something went wrong. Please try again."

    put:
      summary: Update task
      description: Update an existing task (must belong to authenticated user)
      operationId: updateTask
      tags:
        - Tasks
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                emptyTitle:
                  summary: Empty title
                  value:
                    detail: "Task title is required"
                titleTooLong:
                  summary: Title exceeds 200 characters
                  value:
                    detail: "Task title cannot exceed 200 characters"
        '401':
          description: Unauthorized - missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication required"
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "You don't have permission to access this task"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Something went wrong. Please try again."

    delete:
      summary: Delete task
      description: Delete a task permanently (must belong to authenticated user)
      operationId: deleteTask
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication required"
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "You don't have permission to access this task"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Something went wrong. Please try again."

  /tasks/{id}/complete:
    patch:
      summary: Toggle task completion
      description: Toggle task completion status (must belong to authenticated user)
      operationId: toggleTaskComplete
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Task completion toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication required"
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "You don't have permission to access this task"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Something went wrong. Please try again."
